### ISSUE TITLE
Oracledb thin mode:: object of type 'bool' has no len()]

### ISSUE THREAD

**Issue by ivba7** [oracle/python-oracledb#119]
Hi, when calling function:
```
some_out_var = cur.var(str)
result = cur.callfunc('some_test_func',
                                  bool,
                                  ['param1', False, some_out_var])
```
there is error:

Traceback (most recent call last):
  File "/home/r432107/myenv38/lib64/python3.8/site-packages/oracledb/cursor.py", line 261, in callfunc
    self._call(name, parameters, keyword_parameters, var)
  File "/home/r432107/myenv38/lib64/python3.8/site-packages/oracledb/cursor.py", line 116, in _call
    self.execute(statement, bind_values)
  File "/home/r432107/myenv38/lib64/python3.8/site-packages/oracledb/cursor.py", line 378, in execute
    impl.execute(self)
  File "src/oracledb/impl/thin/cursor.pyx", line 133, in oracledb.thin_impl.ThinCursorImpl.execute
  File "src/oracledb/impl/thin/protocol.pyx", line 383, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 384, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 344, in oracledb.thin_impl.Protocol._process_message
  File "src/oracledb/impl/thin/protocol.pyx", line 323, in oracledb.thin_impl.Protocol._process_message
  File "src/oracledb/impl/thin/messages.pyx", line 282, in oracledb.thin_impl.Message.process
  File "src/oracledb/impl/thin/messages.pyx", line 818, in oracledb.thin_impl.MessageWithData._process_message
  File "src/oracledb/impl/thin/messages.pyx", line 898, in oracledb.thin_impl.MessageWithData._process_row_data
  File "src/oracledb/impl/thin/messages.pyx", line 622, in oracledb.thin_impl.MessageWithData._process_column_data
TypeError: object of type 'bool' has no len()

using oracledb 1.2.1

**Comment by anthony-tuininga** [comment]
I am able to replicate your issue. It appears to happen when a null value is returned from the function instead of a `True` or `False` value. I'll look into it further and get back to you with a solution once I have it.

**Comment by anthony-tuininga** [comment]
I have pushed a patch that should correct this issue and added a relevant test case. If you are able to [build from source](https://python-oracledb.readthedocs.io/en/latest/user_guide/installation.html#installing-from-source-code) you can verify that it corrects your issue as well.

**Comment by ivba7** [comment]
Hi,
problem still persists:
oracledb.__version__: 1.3.0b1

File "src/oracledb/impl/thin/cursor.pyx", line 137, in oracledb.thin_impl.ThinCursorImpl.execute
  File "src/oracledb/impl/thin/protocol.pyx", line 383, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 384, in oracledb.thin_impl.Protocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 344, in oracledb.thin_impl.Protocol._process_message
  File "src/oracledb/impl/thin/protocol.pyx", line 323, in oracledb.thin_impl.Protocol._process_message
  File "src/oracledb/impl/thin/messages.pyx", line 282, in oracledb.thin_impl.Message.process
  File "src/oracledb/impl/thin/messages.pyx", line 821, in oracledb.thin_impl.MessageWithData._process_message
  File "src/oracledb/impl/thin/messages.pyx", line 901, in oracledb.thin_impl.MessageWithData._process_row_data
  File "src/oracledb/impl/thin/messages.pyx", line 624, in oracledb.thin_impl.MessageWithData._process_column_data
TypeError: object of type 'bool' has no len()

**Comment by anthony-tuininga** [comment]
That suggests you haven't built with the patch applied? Perhaps confirm that you have the right code and then adjust the value in src/oracledb/version.py to include a different value to ensure that indeed you have built with the patch applied. If that is indeed the case, please provide a complete test case (procedure you are using, complete Python code you are using). Thanks!

**Comment by anthony-tuininga** [comment]
The patches are now in version 1.2.2 which was just released. Please re-open if you still have issues. Thanks!
