### ISSUE TITLE
identified a possible hang in async cursor.executemany()

### ISSUE THREAD

**Issue by zzzeek** [oracle/python-oracledb#278]
hi gang -

our sqlalchemy test suite for the new async oracledb driver we are developing hangs semi-reliably on one particular series of tests that are fielding an intentional IntegrityError from a cursor.executemany() call.

the condition is extremely difficult to reproduce, and I've come up with a script that seems to reproduce it a bit more portably when run on a linux machine, but it still takes many iterations for the condition to hit.   The script below runs the same set of operations over and over again - running it against an Oracle 18c express database here, it will hang usually within 200 iterations.  but i have no idea if it will do this in other circumstances.  if i move the create table step out of the loop, it doesnt hang at all.

```py
import asyncio
import oracledb
import uuid


async def main():
    conn = await oracledb.connect_async(
        dsn="(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=oracle18c)(PORT=1521))(CONNECT_DATA=(SID=xe)))",
        password="tiger",
        user="scott",
    )
    cursor = conn.cursor()

    try:
        await cursor.execute("DROP TABLE data")
    except:
        pass

    cursor.close()

    i = 0
    while True:
        await run_async_thing(conn)
        i += 1
        print(f"finished run: {i}")


async def run_async_thing(conn):
    cursor = conn.cursor()

    await cursor.execute(
        """
CREATE TABLE data (
    id VARCHAR2(30 CHAR) NOT NULL,
    data VARCHAR2(50 CHAR),
    has_server_default VARCHAR2(30 CHAR) DEFAULT 'some_server_default',
    "uid" CHAR(32),
    PRIMARY KEY (id)
)

"""
    )

    ret0, ret1, ret2 = (
        cursor.var(oracledb.STRING, arraysize=10),
        cursor.var(oracledb.STRING, arraysize=10),
        cursor.var(oracledb.STRING, arraysize=10),
    )

    parameters = [
        {
            "data": f"d{i}",
            '"uid"': uuid.uuid4().hex,
            "ret_0": ret0,
            "ret_1": ret1,
            "ret_2": ret2,
        }
        for i in range(10)
    ]

    try:
        await cursor.executemany(
            'INSERT INTO data (data, "uid") VALUES (:data, :"uid") '
            "RETURNING data.id, data.data, data.has_server_default "
            "INTO :ret_0, :ret_1, :ret_2",
            parameters,
        )
    except oracledb.IntegrityError as err:
        print("got error as expected!")

    print("next go!")

    await cursor.execute("DROP TABLE data")
    cursor.close()


asyncio.run(main())

```

so if I run it here it looks like:

```
got error as expected!
next go!
finished run: 1
got error as expected!
next go!
finished run: 2
got error as expected!
next go!
finished run: 3
got error as expected!
next go!
finished run: 4
got error as expected!
next go!

... keeps running ...


finished run: 29
got error as expected!
next go!
finished run: 30
got error as expected!
next go!
finished run: 31

```

then it's hung.  press ctrl-C and stack shows as follows:

```
^CTraceback (most recent call last):
  File "/usr/lib64/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/classic/dev/sqlalchemy/test4.py", line 23, in main
    await run_async_thing(conn)
  File "/home/classic/dev/sqlalchemy/test4.py", line 62, in run_async_thing
    await cursor.executemany(
  File "/home/classic/.venv3/lib64/python3.12/site-packages/oracledb/cursor.py", line 1067, in executemany
    await self._impl.executemany(
  File "src/oracledb/impl/thin/cursor.pyx", line 297, in executemany
  File "src/oracledb/impl/thin/protocol.pyx", line 817, in _process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 818, in oracledb.thin_impl.BaseAsyncProtocol._process_single_message
  File "src/oracledb/impl/thin/protocol.pyx", line 769, in _process_message
  File "src/oracledb/impl/thin/protocol.pyx", line 872, in _reset
  File "src/oracledb/impl/thin/packet.pyx", line 571, in wait_for_packets_async
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test4.py", line 77, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

```

that's what I got so far.  Will see if @caselit can reproduce on his environment.

**Comment by CaselIT** [comment]
Running from windows with oracle on docker (podman on fedora over wsl2 actually) I can't reproduce (stopped with loop over 1700) with 23 (image `gvenzl/oracle-free:23-slim`) and 21 (image `gvenzl/oracle-xe:21-slim`)

With 18 (image `gvenzl/oracle-xe:18-slim`) it tripped at 534. Stack trace below

Maybe it has something to do with version 18 of oracle? 

@zzzeek maybe the best solution is to update the ci to 21 or 23? I'll leave the script running a bit more on 21 to see if it happens

```
Traceback (most recent call last):
  File "C:\Users\cfede\scoop\apps\python\current\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cfede\scoop\apps\python\current\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\cfede\Dev\GitHub\sqlalchemy\test4.py", line 25, in main
    await run_async_thing(conn)
  File "C:\Users\cfede\Dev\GitHub\sqlalchemy\test4.py", line 64, in run_async_thing
    await cursor.executemany(
  File "C:\Users\cfede\venvs\sa\Lib\site-packages\oracledb\cursor.py", line 1067, in executemany
    await self._impl.executemany(
  File "src\\oracledb\\impl/thin/cursor.pyx", line 297, in executemany
  File "src\\oracledb\\impl/thin/protocol.pyx", line 817, in _process_single_message
  File "src\\oracledb\\impl/thin/protocol.pyx", line 818, in oracledb.thin_impl.BaseAsyncProtocol._process_single_message
  File "src\\oracledb\\impl/thin/protocol.pyx", line 769, in _process_message
  File "src\\oracledb\\impl/thin/protocol.pyx", line 872, in _reset
  File "src\\oracledb\\impl/thin/packet.pyx", line 571, in wait_for_packets_async
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cfede\Dev\GitHub\sqlalchemy\test4.py", line 79, in <module>
    asyncio.run(main())
  File "C:\Users\cfede\scoop\apps\python\current\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\cfede\scoop\apps\python\current\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
```

**Comment by CaselIT** [comment]
Just to add that the same suite has run for years using oracledb and cx-oracle with the sync version and it never hanged

**Comment by zzzeek** [comment]
well we can update to 21/23 sure, for now I just have the test marked to skip on oracledb async.    great news it repros!

**Comment by CaselIT** [comment]
>  I'll leave the script running a bit more on 21 to see if it happens

over 25k and it was still running. By this limited test it seems this has something to do with 18 only.

interestingly when I went to stop the 18 container (`gvenzl/oracle-xe:18-slim`) after the script hanged the db did not close cleanly, and got this warning
```
WARN[0010] StopSignal SIGTERM failed to stop container oracle in 10 seconds, resorting to SIGKILL
```

**Comment by anthony-tuininga** [comment]
I noticed with #277 that Python 3.11 and higher do not experience the hang but Python 3.10 and lower do. I also noticed that the uvloop alternative implementation works fine with Python 3.10 and lower. Which Python version are you using? Are you able to try with the uvloop implementation? It may be something specific to the asyncio implementation.

**Comment by zzzeek** [comment]
I get the hang here with python 3.12 and we see it on 3.11 as well

**Comment by anthony-tuininga** [comment]
Ok. Thanks for confirming that. That suggests the issues are unrelated. It was worth checking though!

**Comment by anthony-tuininga** [comment]
I was able to replicate with Oracle Database 18c and discovered that it was a problem with the break/reset mechanism timing. I have pushed a patch that corrects this for me. If you are able to [build from source](https://python-oracledb.readthedocs.io/en/latest/user_guide/installation.html#installing-from-source-code) you can verify that it works for you, too.

**Comment by CaselIT** [comment]
I've tried with 18c on docker installing from source locally and I could no longer reproduce, stopped when the counted was over 26k.

Seems to be fine here.

**Comment by zzzeek** [comment]
yup seems fine now, I confirmed I can still reproduce w/ the old version and the main version fixes the issue.

**Comment by anthony-tuininga** [comment]
Thanks for the confirmation!

**Comment by anthony-tuininga** [comment]
@zzzeek, @CaselIT, I have just pushed this [change](https://github.com/oracle/python-oracledb/commit/86016890b260924e9380d83aff5dcda2dde6cf35) which pretty much reverts the patch that was originally made to resolve this issue. I was able to confirm that the issue remains in the original code prior to the patch but no longer does in the code I just pushed. Just to be safe, if you could run the code as well with this commit and verify that it is not an issue for you, that would be appreciated. I believe other changes have eliminated the original issue, but I'd like to be sure!

**Comment by zzzeek** [comment]
is there any quick way to build just the thin client without it looking for OCI for the thick client?  or can you put up a wheel file somewhere

**Comment by anthony-tuininga** [comment]
The build of the driver doesn't require OCI or the thick client in any way. You can simply [build from source](https://python-oracledb.readthedocs.io/en/latest/user_guide/installation.html#installing-from-source-code). That said, I believe I was able to confirm that the original issue reported here has been corrected a different way -- so this is just paranoia, I think!

**Comment by zzzeek** [comment]
OK I dont want to crowd up the issue here with unrelated things, note I'm not looking very hard at this but a basic build errors out for me

```
$ python setup.py  build
/home/classic/.venv3/lib64/python3.12/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
WARNING: The wheel package is not available.
WARNING setuptools_scm._integration.setuptools pyproject.toml does not contain a tool.setuptools_scm section
running build
running build_py
running build_ext
Compiling src/oracledb/base_impl.pyx because it changed.
[1/1] Cythonizing src/oracledb/base_impl.pyx
building 'oracledb.base_impl' extension
gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fPIC -I/home/classic/.venv3/include -I/usr/include/python3.12 -c src/oracledb/base_impl.c -o build/temp.linux-x86_64-cpython-312/src/oracledb/base_impl.o
gcc -shared build/temp.linux-x86_64-cpython-312/src/oracledb/base_impl.o -L/usr/lib64 -o build/lib.linux-x86_64-cpython-312/oracledb/base_impl.cpython-312-x86_64-linux-gnu.so
Compiling src/oracledb/thin_impl.pyx because it changed.
[1/1] Cythonizing src/oracledb/thin_impl.pyx
building 'oracledb.thin_impl' extension
gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fPIC -I/home/classic/.venv3/include -I/usr/include/python3.12 -c src/oracledb/thin_impl.c -o build/temp.linux-x86_64-cpython-312/src/oracledb/thin_impl.o
src/oracledb/thin_impl.c: In function ‘__pyx_f_8oracledb_9thin_impl_15MessageWithData__get_bit_vector’:
src/oracledb/thin_impl.c:59807:73: error: passing argument 1 of ‘__pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes’ from incompatible pointer type [-Wincompatible-pointer-types]
59807 |   __pyx_t_1 = __pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes(((struct __pyx_obj_8oracledb_9base_impl_Buffer *)__pyx_v_buf), __pyx_v_num_bytes); if (unlikely(__pyx_t_1 == ((__pyx_t_8oracledb_9base_impl_char_type const *)NULL))) __PYX_ERR(4, 391, __pyx_L1_error)
      |                                                                        ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                         |
      |                                                                         struct __pyx_obj_8oracledb_9base_impl_Buffer *
src/oracledb/thin_impl.c:51574:161: note: expected ‘struct __pyx_obj_8oracledb_9thin_impl_ReadBuffer *’ but argument is of type ‘struct __pyx_obj_8oracledb_9base_impl_Buffer *’
51574 | oracledb_9thin_impl_char_type const *__pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes(struct __pyx_obj_8oracledb_9thin_impl_ReadBuffer *__pyx_v_self, Py_ssize_t __pyx_v_num_bytes) {
      |                                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~

src/oracledb/thin_impl.c: In function ‘__pyx_f_8oracledb_9thin_impl_14ConnectMessage_process’:
src/oracledb/thin_impl.c:79842:75: error: passing argument 1 of ‘__pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes’ from incompatible pointer type [-Wincompatible-pointer-types]
79842 |     __pyx_t_3 = __pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes(((struct __pyx_obj_8oracledb_9base_impl_Buffer *)__pyx_v_buf), __pyx_v_self->redirect_data_len); if (unlikely(__pyx_t_3 == ((__pyx_t_8oracledb_9base_impl_char_type const *)NULL))) __PYX_ERR(4, 1837, __pyx_L1_error)
      |                                                                          ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                           |
      |                                                                           struct __pyx_obj_8oracledb_9base_impl_Buffer *
src/oracledb/thin_impl.c:51574:161: note: expected ‘struct __pyx_obj_8oracledb_9thin_impl_ReadBuffer *’ but argument is of type ‘struct __pyx_obj_8oracledb_9base_impl_Buffer *’
51574 | oracledb_9thin_impl_char_type const *__pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes(struct __pyx_obj_8oracledb_9thin_impl_ReadBuffer *__pyx_v_self, Py_ssize_t __pyx_v_num_bytes) {
      |                                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~

src/oracledb/thin_impl.c: In function ‘__pyx_f_8oracledb_9thin_impl_12LobOpMessage__process_return_parameters’:
src/oracledb/thin_impl.c:86480:75: error: passing argument 1 of ‘__pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes’ from incompatible pointer type [-Wincompatible-pointer-types]
86480 |     __pyx_t_4 = __pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes(((struct __pyx_obj_8oracledb_9base_impl_Buffer *)__pyx_v_buf), __pyx_v_num_bytes); if (unlikely(__pyx_t_4 == ((__pyx_t_8oracledb_9base_impl_char_type const *)NULL))) __PYX_ERR(4, 2258, __pyx_L1_error)
      |                                                                          ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                           |
      |                                                                           struct __pyx_obj_8oracledb_9base_impl_Buffer *
src/oracledb/thin_impl.c:51574:161: note: expected ‘struct __pyx_obj_8oracledb_9thin_impl_ReadBuffer *’ but argument is of type ‘struct __pyx_obj_8oracledb_9base_impl_Buffer *’
51574 | oracledb_9thin_impl_char_type const *__pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes(struct __pyx_obj_8oracledb_9thin_impl_ReadBuffer *__pyx_v_self, Py_ssize_t __pyx_v_num_bytes) {
      |                                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~

src/oracledb/thin_impl.c:86541:75: error: passing argument 1 of ‘__pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes’ from incompatible pointer type [-Wincompatible-pointer-types]
86541 |     __pyx_t_4 = __pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes(((struct __pyx_obj_8oracledb_9base_impl_Buffer *)__pyx_v_buf), __pyx_v_num_bytes); if (unlikely(__pyx_t_4 == ((__pyx_t_8oracledb_9base_impl_char_type const *)NULL))) __PYX_ERR(4, 2262, __pyx_L1_error)
      |                                                                          ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                           |
      |                                                                           struct __pyx_obj_8oracledb_9base_impl_Buffer *
src/oracledb/thin_impl.c:51574:161: note: expected ‘struct __pyx_obj_8oracledb_9thin_impl_ReadBuffer *’ but argument is of type ‘struct __pyx_obj_8oracledb_9base_impl_Buffer *’
51574 | oracledb_9thin_impl_char_type const *__pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes(struct __pyx_obj_8oracledb_9thin_impl_ReadBuffer *__pyx_v_self, Py_ssize_t __pyx_v_num_bytes) {
      |                                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~

src/oracledb/thin_impl.c: In function ‘__pyx_f_8oracledb_9thin_impl_15ProtocolMessage__process_protocol_info’:
src/oracledb/thin_impl.c:89203:73: error: passing argument 1 of ‘__pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes’ from incompatible pointer type [-Wincompatible-pointer-types]
89203 |   __pyx_t_5 = __pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes(((struct __pyx_obj_8oracledb_9base_impl_Buffer *)__pyx_v_buf), __pyx_v_fdo_length); if (unlikely(__pyx_t_5 == ((__pyx_t_8oracledb_9base_impl_char_type const *)NULL))) __PYX_ERR(4, 2392, __pyx_L1_error)
      |                                                                        ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                         |
      |                                                                         struct __pyx_obj_8oracledb_9base_impl_Buffer *
src/oracledb/thin_impl.c:51574:161: note: expected ‘struct __pyx_obj_8oracledb_9thin_impl_ReadBuffer *’ but argument is of type ‘struct __pyx_obj_8oracledb_9base_impl_Buffer *’
51574 | oracledb_9thin_impl_char_type const *__pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes(struct __pyx_obj_8oracledb_9thin_impl_ReadBuffer *__pyx_v_self, Py_ssize_t __pyx_v_num_bytes) {
      |                                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~

src/oracledb/thin_impl.c: In function ‘__pyx_f_8oracledb_9thin_impl_8Protocol__receive_packet’:
src/oracledb/thin_impl.c:97099:77: error: passing argument 1 of ‘__pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes’ from incompatible pointer type [-Wincompatible-pointer-types]
97099 |       __pyx_t_4 = __pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes(((struct __pyx_obj_8oracledb_9base_impl_Buffer *)__pyx_v_buf), __pyx_v_refuse_message_len); if (unlikely(__pyx_t_4 == ((__pyx_t_8oracledb_9base_impl_char_type const *)NULL))) __PYX_ERR(13, 463, __pyx_L1_error)
      |                                                                            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                             |
      |                                                                             struct __pyx_obj_8oracledb_9base_impl_Buffer *
src/oracledb/thin_impl.c:51574:161: note: expected ‘struct __pyx_obj_8oracledb_9thin_impl_ReadBuffer *’ but argument is of type ‘struct __pyx_obj_8oracledb_9base_impl_Buffer *’
51574 | oracledb_9thin_impl_char_type const *__pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes(struct __pyx_obj_8oracledb_9thin_impl_ReadBuffer *__pyx_v_self, Py_ssize_t __pyx_v_num_bytes) {
      |                                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~

src/oracledb/thin_impl.c: In function ‘__pyx_gb_8oracledb_9thin_impl_17BaseAsyncProtocol_28generator12’:
src/oracledb/thin_impl.c:105403:77: error: passing argument 1 of ‘__pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes’ from incompatible pointer type [-Wincompatible-pointer-types]
105403 |       __pyx_t_6 = __pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes(((struct __pyx_obj_8oracledb_9base_impl_Buffer *)__pyx_cur_scope->__pyx_v_buf), __pyx_cur_scope->__pyx_v_refuse_message_len); if (unlikely(__pyx_t_6 == ((__pyx_t_8oracledb_9base_impl_char_type const *)NULL))) __PYX_ERR(13, 841, __pyx_L1_error)
       |                                                                            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       |                                                                             |
       |                                                                             struct __pyx_obj_8oracledb_9base_impl_Buffer *
src/oracledb/thin_impl.c:51574:161: note: expected ‘struct __pyx_obj_8oracledb_9thin_impl_ReadBuffer *’ but argument is of type ‘struct __pyx_obj_8oracledb_9base_impl_Buffer *’
51574 | oracledb_9thin_impl_char_type const *__pyx_f_8oracledb_9thin_impl_10ReadBuffer_read_raw_bytes(struct __pyx_obj_8oracledb_9thin_impl_ReadBuffer *__pyx_v_self, Py_ssize_t __pyx_v_num_bytes) {
      |                                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~

error: command '/usr/bin/gcc' failed with exit code 1

```

**Comment by zzzeek** [comment]
pip install fails differently, inside the thick impl

```
$ pip install .
Processing /home/classic/dev/python-oracledb
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cryptography>=3.2.1 in /home/classic/.venv3/lib64/python3.12/site-packages (from oracledb==2.3.0b1) (41.0.5)
Requirement already satisfied: cffi>=1.12 in /home/classic/.venv3/lib64/python3.12/site-packages (from cryptography>=3.2.1->oracledb==2.3.0b1) (1.16.0)
Requirement already satisfied: pycparser in /home/classic/.venv3/lib64/python3.12/site-packages (from cffi>=1.12->cryptography>=3.2.1->oracledb==2.3.0b1) (2.21)
Building wheels for collected packages: oracledb
  Building wheel for oracledb (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for oracledb (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [163 lines of output]
      running bdist_wheel
      running build
      running build_py
      copying src/oracledb/aq.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/constructors.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/driver_mode.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/dsn.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/exceptions.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/future.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/subscr.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/var.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/__init__.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/connect_params.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/connection.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/constants.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/cursor.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/dbobject.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/defaults.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/errors.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/fetch_info.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/lob.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/pool.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/pool_params.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/soda.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/utils.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/version.py -> build/lib.linux-x86_64-cpython-312/oracledb
      copying src/oracledb/py.typed -> build/lib.linux-x86_64-cpython-312/oracledb
      running build_ext
      Compiling src/oracledb/base_impl.pyx because it changed.
      [1/1] Cythonizing src/oracledb/base_impl.pyx
      building 'oracledb.base_impl' extension
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fPIC -I/home/classic/.venv3/include -I/usr/include/python3.12 -c src/oracledb/base_impl.c -o build/temp.linux-x86_64-cpython-312/src/oracledb/base_impl.o
      gcc -shared build/temp.linux-x86_64-cpython-312/src/oracledb/base_impl.o -L/usr/lib64 -o build/lib.linux-x86_64-cpython-312/oracledb/base_impl.cpython-312-x86_64-linux-gnu.so
      Compiling src/oracledb/thin_impl.pyx because it changed.
      [1/1] Cythonizing src/oracledb/thin_impl.pyx
      building 'oracledb.thin_impl' extension
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fPIC -I/home/classic/.venv3/include -I/usr/include/python3.12 -c src/oracledb/thin_impl.c -o build/temp.linux-x86_64-cpython-312/src/oracledb/thin_impl.o
      gcc -shared build/temp.linux-x86_64-cpython-312/src/oracledb/thin_impl.o -L/usr/lib64 -o build/lib.linux-x86_64-cpython-312/oracledb/thin_impl.cpython-312-x86_64-linux-gnu.so
      Compiling src/oracledb/thick_impl.pyx because it depends on /tmp/pip-build-env-gi8jmb_b/overlay/lib64/python3.12/site-packages/Cython/Includes/libc/stdio.pxd.
      [1/1] Cythonizing src/oracledb/thick_impl.pyx
      building 'oracledb.thick_impl' extension
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fPIC -Isrc/oracledb/impl/thick/odpi/include -I/home/classic/.venv3/include -I/usr/include/python3.12 -c src/oracledb/thick_impl.c -o build/temp.linux-x86_64-cpython-312/src/oracledb/thick_impl.o
      src/oracledb/thick_impl.c:5816:75: error: unknown type name ‘dpiVector’
       5816 | static PyObject *__pyx_f_8oracledb_10thick_impl__convert_vector_to_python(dpiVector *); /*proto*/
            |                                                                           ^~~~~~~~~
      src/oracledb/thick_impl.c: In function ‘__pyx_f_8oracledb_10thick_impl_15ThickCursorImpl__define_var’:
      src/oracledb/thick_impl.c:49994:34: error: ‘dpiDataTypeInfo’ has no member named ‘isOson’; did you mean ‘isJson’?
      49994 |   __pyx_t_1 = __pyx_v_type_info->isOson;
            |                                  ^~~~~~
            |                                  isJson
      src/oracledb/thick_impl.c:50257:51: error: ‘DPI_ORACLE_TYPE_VECTOR’ undeclared (first use in this function); did you mean ‘DPI_ORACLE_TYPE_NCLOB’?
      50257 |   __pyx_t_1 = (__pyx_v_fetch_info->dbtype->num == DPI_ORACLE_TYPE_VECTOR);
            |                                                   ^~~~~~~~~~~~~~~~~~~~~~
            |                                                   DPI_ORACLE_TYPE_NCLOB
      src/oracledb/thick_impl.c:50257:51: note: each undeclared identifier is reported only once for each function it appears in
      src/oracledb/thick_impl.c:50267:34: error: ‘dpiDataTypeInfo’ has no member named ‘vectorDimensions’
      50267 |     __pyx_t_4 = __pyx_v_type_info->vectorDimensions;
            |                                  ^~
      src/oracledb/thick_impl.c:50277:35: error: ‘dpiDataTypeInfo’ has no member named ‘vectorFormat’
      50277 |     __pyx_t_10 = __pyx_v_type_info->vectorFormat;
            |                                   ^~
      src/oracledb/thick_impl.c:50287:35: error: ‘dpiDataTypeInfo’ has no member named ‘vectorFlags’
      50287 |     __pyx_t_10 = __pyx_v_type_info->vectorFlags;
            |                                   ^~
      src/oracledb/thick_impl.c: In function ‘__pyx_f_8oracledb_10thick_impl_10JsonBuffer__populate_node’:
      src/oracledb/thick_impl.c:59455:19: error: ‘DPI_ORACLE_TYPE_JSON_ID’ undeclared (first use in this function); did you mean ‘DPI_ORACLE_TYPE_JSON’?
      59455 |       __pyx_t_3 = DPI_ORACLE_TYPE_JSON_ID;
            |                   ^~~~~~~~~~~~~~~~~~~~~~~
            |                   DPI_ORACLE_TYPE_JSON
      src/oracledb/thick_impl.c:60020:35: error: ‘DPI_ORACLE_TYPE_VECTOR’ undeclared (first use in this function); did you mean ‘DPI_ORACLE_TYPE_NCLOB’?
      60020 |     __pyx_v_node->oracleTypeNum = DPI_ORACLE_TYPE_VECTOR;
            |                                   ^~~~~~~~~~~~~~~~~~~~~~
            |                                   DPI_ORACLE_TYPE_NCLOB
      src/oracledb/thick_impl.c: In function ‘__pyx_pf_8oracledb_10thick_impl_15ThickSodaDbImpl_6create_json_document’:
      src/oracledb/thick_impl.c:69915:16: error: implicit declaration of function ‘dpiSodaDb_createJsonDocument’; did you mean ‘dpiSodaDb_createDocument’? [-Wimplicit-function-declaration]
      69915 |   __pyx_t_3 = (dpiSodaDb_createJsonDocument(__pyx_v_self->_handle, __pyx_v_key_buf->ptr, __pyx_v_key_buf->length, (&__pyx_v_json_buf->_top_node), DPI_SODA_FLAGS_DEFAULT, (&__pyx_v_doc_impl->_handle)) < 0);
            |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
            |                dpiSodaDb_createDocument
      src/oracledb/thick_impl.c: In function ‘__pyx_pf_8oracledb_10thick_impl_16ThickSodaDocImpl_2get_content’:
      src/oracledb/thick_impl.c:75530:16: error: implicit declaration of function ‘dpiSodaDoc_getIsJson’; did you mean ‘dpiSodaDoc_getVersion’? [-Wimplicit-function-declaration]
      75530 |   __pyx_t_1 = (dpiSodaDoc_getIsJson(__pyx_v_self->_handle, (&__pyx_v_is_json)) < 0);
            |                ^~~~~~~~~~~~~~~~~~~~
            |                dpiSodaDoc_getVersion
      src/oracledb/thick_impl.c:75567:18: error: implicit declaration of function ‘dpiSodaDoc_getJsonContent’; did you mean ‘dpiSodaDoc_getContent’? [-Wimplicit-function-declaration]
      75567 |     __pyx_t_1 = (dpiSodaDoc_getJsonContent(__pyx_v_self->_handle, (&__pyx_v_json)) < 0);
            |                  ^~~~~~~~~~~~~~~~~~~~~~~~~
            |                  dpiSodaDoc_getContent
      src/oracledb/thick_impl.c: In function ‘__pyx_f_8oracledb_10thick_impl__convert_from_json_node’:
      src/oracledb/thick_impl.c:91317:47: error: ‘DPI_ORACLE_TYPE_VECTOR’ undeclared (first use in this function); did you mean ‘DPI_ORACLE_TYPE_NCLOB’?
      91317 |   __pyx_t_1 = (__pyx_v_node->oracleTypeNum == DPI_ORACLE_TYPE_VECTOR);
            |                                               ^~~~~~~~~~~~~~~~~~~~~~
            |                                               DPI_ORACLE_TYPE_NCLOB
      src/oracledb/thick_impl.c:91375:47: error: ‘DPI_ORACLE_TYPE_JSON_ID’ undeclared (first use in this function); did you mean ‘DPI_ORACLE_TYPE_JSON’?
      91375 |   __pyx_t_1 = (__pyx_v_node->oracleTypeNum == DPI_ORACLE_TYPE_JSON_ID);
            |                                               ^~~~~~~~~~~~~~~~~~~~~~~
            |                                               DPI_ORACLE_TYPE_JSON
      src/oracledb/thick_impl.c: In function ‘__pyx_f_8oracledb_10thick_impl__convert_from_python’:
      src/oracledb/thick_impl.c:91508:3: error: unknown type name ‘dpiVectorInfo’; did you mean ‘dpiErrorInfo’?
      91508 |   dpiVectorInfo __pyx_v_vector_info;
            |   ^~~~~~~~~~~~~
            |   dpiErrorInfo
      src/oracledb/thick_impl.c:92572:10: error: ‘DPI_ORACLE_TYPE_VECTOR’ undeclared (first use in this function); did you mean ‘DPI_ORACLE_TYPE_NCLOB’?
      92572 |     case DPI_ORACLE_TYPE_VECTOR:
            |          ^~~~~~~~~~~~~~~~~~~~~~
            |          DPI_ORACLE_TYPE_NCLOB
      src/oracledb/thick_impl.c:92594:26: error: request for member ‘format’ in something not a structure or union
      92594 |       __pyx_v_vector_info.format = DPI_VECTOR_FORMAT_FLOAT64;
            |                          ^
      src/oracledb/thick_impl.c:92594:36: error: ‘DPI_VECTOR_FORMAT_FLOAT64’ undeclared (first use in this function)
      92594 |       __pyx_v_vector_info.format = DPI_VECTOR_FORMAT_FLOAT64;
            |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
      src/oracledb/thick_impl.c:92626:26: error: request for member ‘format’ in something not a structure or union
      92626 |       __pyx_v_vector_info.format = DPI_VECTOR_FORMAT_FLOAT32;
            |                          ^
      src/oracledb/thick_impl.c:92626:36: error: ‘DPI_VECTOR_FORMAT_FLOAT32’ undeclared (first use in this function)
      92626 |       __pyx_v_vector_info.format = DPI_VECTOR_FORMAT_FLOAT32;
            |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
      src/oracledb/thick_impl.c:92646:26: error: request for member ‘format’ in something not a structure or union
      92646 |       __pyx_v_vector_info.format = DPI_VECTOR_FORMAT_INT8;
            |                          ^
      src/oracledb/thick_impl.c:92646:36: error: ‘DPI_VECTOR_FORMAT_INT8’ undeclared (first use in this function)
      92646 |       __pyx_v_vector_info.format = DPI_VECTOR_FORMAT_INT8;
            |                                    ^~~~~~~~~~~~~~~~~~~~~~
      src/oracledb/thick_impl.c:92658:24: error: request for member ‘numDimensions’ in something not a structure or union
      92658 |     __pyx_v_vector_info.numDimensions = ((uint32_t)__pyx_t_13);
            |                        ^
      src/oracledb/thick_impl.c:92668:24: error: request for member ‘dimensions’ in something not a structure or union
      92668 |     __pyx_v_vector_info.dimensions.asPtr = __pyx_t_14;
            |                        ^
      src/oracledb/thick_impl.c:92677:18: error: implicit declaration of function ‘dpiVector_setValue’; did you mean ‘dpiVar__setValue’? [-Wimplicit-function-declaration]
      92677 |     __pyx_t_5 = (dpiVector_setValue(__pyx_v_dbvalue->asVector, (&__pyx_v_vector_info)) < 0);
            |                  ^~~~~~~~~~~~~~~~~~
            |                  dpiVar__setValue
      src/oracledb/thick_impl.c:92677:52: error: ‘dpiDataBuffer’ has no member named ‘asVector’
      92677 |     __pyx_t_5 = (dpiVector_setValue(__pyx_v_dbvalue->asVector, (&__pyx_v_vector_info)) < 0);
            |                                                    ^~
      src/oracledb/thick_impl.c: In function ‘__pyx_f_8oracledb_10thick_impl__convert_to_python’:
      src/oracledb/thick_impl.c:94339:10: error: ‘DPI_ORACLE_TYPE_VECTOR’ undeclared (first use in this function); did you mean ‘DPI_ORACLE_TYPE_NCLOB’?
      94339 |     case DPI_ORACLE_TYPE_VECTOR:
            |          ^~~~~~~~~~~~~~~~~~~~~~
            |          DPI_ORACLE_TYPE_NCLOB
      src/oracledb/thick_impl.c:94349:17: error: implicit declaration of function ‘__pyx_f_8oracledb_10thick_impl__convert_vector_to_python’; did you mean ‘__pyx_f_8oracledb_10thick_impl__convert_json_to_python’? [-Wimplicit-function-declaration]
      94349 |     __pyx_t_2 = __pyx_f_8oracledb_10thick_impl__convert_vector_to_python(__pyx_v_dbvalue->asVector); if (unlikely(!__pyx_t_2)) __PYX_ERR(16, 381, __pyx_L1_error)
            |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            |                 __pyx_f_8oracledb_10thick_impl__convert_json_to_python
      src/oracledb/thick_impl.c:94349:89: error: ‘dpiDataBuffer’ has no member named ‘asVector’
      94349 |     __pyx_t_2 = __pyx_f_8oracledb_10thick_impl__convert_vector_to_python(__pyx_v_dbvalue->asVector); if (unlikely(!__pyx_t_2)) __PYX_ERR(16, 381, __pyx_L1_error)
            |                                                                                         ^~
      src/oracledb/thick_impl.c: At top level:
      src/oracledb/thick_impl.c:94485:75: error: unknown type name ‘dpiVector’
      94485 | static PyObject *__pyx_f_8oracledb_10thick_impl__convert_vector_to_python(dpiVector *__pyx_v_vector) {
            |                                                                           ^~~~~~~~~
      src/oracledb/thick_impl.c: In function ‘__pyx_pf_8oracledb_10thick_impl_2init_oracle_client’:
      src/oracledb/thick_impl.c:95843:25: error: ‘dpiContextCreateParams’ has no member named ‘sodaUseJsonDesc’
      95843 |           __pyx_v_params.sodaUseJsonDesc = __pyx_t_2;
            |                         ^
      src/oracledb/thick_impl.c:95852:25: error: ‘dpiContextCreateParams’ has no member named ‘useJsonId’
      95852 |           __pyx_v_params.useJsonId = 1;
            |                         ^
      src/oracledb/thick_impl.c:96298:37: error: ‘dpiContextCreateParams’ has no member named ‘sodaUseJsonDesc’
      96298 |           __pyx_t_2 = __pyx_v_params.sodaUseJsonDesc;
            |                                     ^
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for oracledb
Failed to build oracledb
ERROR: Could not build wheels for oracledb, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip install --upgrade pip

```

**Comment by anthony-tuininga** [comment]
Hmm, not sure what that is all about! What platform are you running on? I can post a Python3.12 wheel here for you and then destroy it later -- and remove these extraneous posts.

**Comment by zzzeek** [comment]
yes taht was it, the submodules needed to be refreshed.  i dont know how to do that so I blew everything away and re-cloned

**Comment by anthony-tuininga** [comment]
Thanks, @zzzeek!
